/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.*;
import static View.ManageBooks.controller;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abokh
 */
public class IssueBook extends javax.swing.JFrame {

    public static AppControl controller;
    public FileAccess fileAccess;

    public IssueBook() {

        fileAccess = new FileAccess();
        initComponents();
        controller = new AppControl();
         String coltitle[] = {"Student ID", "Student Name", "Education Level", "Major"};
        String data[][] = controller.getStudentdata();
        DefaultTableModel model = new DefaultTableModel(data, coltitle);
        studentsTable.setModel(model);
        String coltitle1[] = {"Book ID", "Book Name", "Author", "Quantity"};
        String data1[][] = controller.getBooksdata();
        DefaultTableModel model1 = new DefaultTableModel(data1, coltitle1);
        booksTable.setModel(model1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JLabel();
        txtStudentId = new app.bolivia.swing.JCTextField();
        txtBookId = new app.bolivia.swing.JCTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        butIssueBook1 = new necesario.RSMaterialButtonCircle();
        jLabel34 = new javax.swing.JLabel();
        IssuedDate = new app.bolivia.swing.JCTextField();
        ReturnDate = new app.bolivia.swing.JCTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        booksTable = new rojeru_san.complementos.RSTableMetro();
        jScrollPane6 = new javax.swing.JScrollPane();
        studentsTable = new rojeru_san.complementos.RSTableMetro();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(101, 0, 101));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/IssueBook/icons8_course_100px_1.png"))); // NOI18N
        jLabel3.setText("Issue Book");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 8, 0, new java.awt.Color(101, 0, 101)));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 50, -1, -1));

        jLabel17.setFont(new java.awt.Font("Malgun Gothic", 3, 25)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Signup/icons8_multiply_48px.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1800, 0, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(101, 0, 101));
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/IssueBook/icons8_course_100px_1.png"))); // NOI18N
        jLabel29.setText("Issue Book");
        jLabel29.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 8, 0, new java.awt.Color(101, 0, 101)));
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 50, -1, -1));

        txtQuantity.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        txtQuantity.setForeground(new java.awt.Color(101, 0, 101));
        txtQuantity.setText("Quantity :");
        jPanel5.add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 630, 170, -1));

        txtStudentId.setEditable(false);
        txtStudentId.setBackground(new java.awt.Color(255, 255, 255));
        txtStudentId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(101, 0, 101)));
        txtStudentId.setForeground(new java.awt.Color(0, 0, 0));
        txtStudentId.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        txtStudentId.setPlaceholder("Student Name ...");
        txtStudentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentIdActionPerformed(evt);
            }
        });
        jPanel5.add(txtStudentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 380, 340, -1));

        txtBookId.setEditable(false);
        txtBookId.setBackground(new java.awt.Color(255, 255, 255));
        txtBookId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(101, 0, 101)));
        txtBookId.setForeground(new java.awt.Color(0, 0, 0));
        txtBookId.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        txtBookId.setPlaceholder("Book Name ...");
        jPanel5.add(txtBookId, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 280, 340, -1));

        jLabel32.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(101, 0, 101));
        jLabel32.setText("Student Name :");
        jPanel5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 390, 190, -1));

        jLabel33.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(101, 0, 101));
        jLabel33.setText("Return Date :");
        jPanel5.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 580, 150, -1));

        butIssueBook1.setBackground(new java.awt.Color(101, 0, 101));
        butIssueBook1.setText("Issue Book");
        butIssueBook1.setToolTipText("");
        butIssueBook1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butIssueBook1ActionPerformed(evt);
            }
        });
        jPanel5.add(butIssueBook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 680, 500, 90));

        jLabel34.setFont(new java.awt.Font("Malgun Gothic", 3, 25)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(204, 204, 204));
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Signup/icons8_multiply_48px.png"))); // NOI18N
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(1800, 0, -1, -1));

        IssuedDate.setBackground(new java.awt.Color(255, 255, 255));
        IssuedDate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(101, 0, 101)));
        IssuedDate.setForeground(new java.awt.Color(0, 0, 0));
        IssuedDate.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        IssuedDate.setPlaceholder("Enter Issue Date ...");
        jPanel5.add(IssuedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 470, 340, -1));

        ReturnDate.setBackground(new java.awt.Color(255, 255, 255));
        ReturnDate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(101, 0, 101)));
        ReturnDate.setForeground(new java.awt.Color(0, 0, 0));
        ReturnDate.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        ReturnDate.setPlaceholder("Enter Return date ...");
        ReturnDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnDateActionPerformed(evt);
            }
        });
        jPanel5.add(ReturnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 570, 340, -1));

        jLabel13.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(101, 0, 101));
        jLabel13.setText("Issue date:");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 480, 190, -1));

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(101, 0, 101));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/ReturnBook/icons8_important_book_100px.png"))); // NOI18N
        jLabel2.setText("Serlect A Book And student From The table");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 8, 0, new java.awt.Color(101, 0, 101)));

        booksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Book ID", "Book Name", "Author", "Quanitity"
            }
        ));
        booksTable.setColorBackgoundHead(new java.awt.Color(101, 0, 101));
        booksTable.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        booksTable.setFuenteFilas(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        booksTable.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        booksTable.setFuenteHead(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        booksTable.setRowHeight(40);
        booksTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booksTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(booksTable);

        studentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student ID", "Student Name", "Education Level", "Major"
            }
        ));
        studentsTable.setColorBackgoundHead(new java.awt.Color(101, 0, 101));
        studentsTable.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        studentsTable.setFuenteFilas(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        studentsTable.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        studentsTable.setFuenteHead(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        studentsTable.setRowHeight(40);
        studentsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentsTableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(studentsTable);

        jPanel4.setBackground(new java.awt.Color(102, 153, 255));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/ManageBooks/icons8_back_to_48px.png"))); // NOI18N
        jLabel1.setText("Back");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 50));

        jLabel48.setBackground(new java.awt.Color(120, 120, 120));
        jLabel48.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("Students Info");

        jLabel50.setBackground(new java.awt.Color(120, 120, 120));
        jLabel50.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 0, 0));
        jLabel50.setText("Books Info");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel48)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1120, Short.MAX_VALUE)
                                .addComponent(jScrollPane5))
                            .addComponent(jLabel50)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1150, 950));

        jLabel35.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(101, 0, 101));
        jLabel35.setText("Book Name :");
        jPanel5.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 290, 170, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnDateActionPerformed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void txtStudentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentIdActionPerformed

    private void butIssueBook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butIssueBook1ActionPerformed
     
        String bookName = txtBookId.getText();
        String studentName = txtStudentId.getText();
        String IssueDate = IssuedDate.getText();
        String ReturnDate = this.ReturnDate.getText();
        if (bookName.isEmpty() || studentName.isEmpty()
                || IssueDate.isEmpty() || ReturnDate.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter all the informations to add the book");

        } 
        else {
//              DefaultTableModel  defaultTableModel = (DefaultTableModel)booksTable.getModel();
//             String bookId1 =  defaultTableModel.getValueAt(booksTable.getSelectedRow(), 0).toString();
//             String bookName1 =  defaultTableModel.getValueAt(booksTable.getSelectedRow(), 1).toString();
//             String bookAuthor1 =  defaultTableModel.getValueAt(booksTable.getSelectedRow(), 2).toString();
//             String bookQuantity1 =  defaultTableModel.getValueAt(booksTable.getSelectedRow(), 3).toString();
//             int newQuantity = Integer.parseInt(bookQuantity1)-1;
//            fileAccess.editBooksQuantity(fileAccess.FILEBOOK, bookQuantity1 , 5, bookId1,bookName1, bookAuthor1,newQuantity);
            controller.addIssuedBook(txtBookId.getText(), txtStudentId.getText(), IssuedDate.getText(), this.ReturnDate.getText(), "Pending");
            JOptionPane.showMessageDialog(this, "Book added succesfully");
            txtBookId.setText("");
            txtStudentId.setText("");
            this.ReturnDate.setText("");
            this.IssuedDate.setText("");
        }
    }//GEN-LAST:event_butIssueBook1ActionPerformed
 public int getIssuedBooksCount() {
        return fileAccess.readIssuedBooks().size();
    }
    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel34MouseClicked

    private void booksTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksTableMouseClicked
        DefaultTableModel  defaultTableModel = (DefaultTableModel)booksTable.getModel();
        String bookName =  defaultTableModel.getValueAt(booksTable.getSelectedRow(), 1).toString();
        String Quantity =  defaultTableModel.getValueAt(booksTable.getSelectedRow(), 3).toString();
        
        // set the data on the lables
        txtBookId.setText(bookName);
        txtQuantity.setText(Quantity);
    }//GEN-LAST:event_booksTableMouseClicked

    private void studentsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentsTableMouseClicked
        DefaultTableModel  defaultTableModel = (DefaultTableModel)studentsTable.getModel();
        String studentName =  defaultTableModel.getValueAt(studentsTable.getSelectedRow(), 1).toString();

        // set the data on the lables
        txtStudentId.setText(studentName);
    }//GEN-LAST:event_studentsTableMouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked

    }//GEN-LAST:event_jPanel4MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        HomePage homePage = new HomePage();
        homePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IssueBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.bolivia.swing.JCTextField IssuedDate;
    private app.bolivia.swing.JCTextField ReturnDate;
    private rojeru_san.complementos.RSTableMetro booksTable;
    private necesario.RSMaterialButtonCircle butIssueBook1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private rojeru_san.complementos.RSTableMetro studentsTable;
    private app.bolivia.swing.JCTextField txtBookId;
    private javax.swing.JLabel txtQuantity;
    private app.bolivia.swing.JCTextField txtStudentId;
    // End of variables declaration//GEN-END:variables
}
