/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.*;
import static View.ViewIssuedBooks.controller;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author abokh
 */
public class ReturnBook extends javax.swing.JFrame {

    /**
     * Creates new form IssueBook
     */
      public static AppControl controller;
    public FileAccess fileAccess;
    public ReturnBook() {
        fileAccess = new FileAccess();
        initComponents();
        controller = new AppControl();
        String coltitle[] = {"Student ID", "Student Name", "Education Level", "Major"};
        String data[][] = controller.getStudentdata();
        DefaultTableModel model = new DefaultTableModel(data, coltitle);
        studentsTable.setModel(model);
        String coltitle1[] = {"Book ID", "Book Name", "Author", "Quantity"};
        String data1[][] = controller.getBooksdata();
        DefaultTableModel model1 = new DefaultTableModel(data1, coltitle1);
        booksTable.setModel(model1);
        String coltitle2[] = {"Book Name", "Student Name", "Issued Date", "Return Date","Status"};
        String data2[][] = controller.getIssuedBooksdata();
        DefaultTableModel model2 = new DefaultTableModel(data2, coltitle2);
        issuedBooksTable.setModel(model2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        booksTable = new rojeru_san.complementos.RSTableMetro();
        jScrollPane6 = new javax.swing.JScrollPane();
        studentsTable = new rojeru_san.complementos.RSTableMetro();
        jScrollPane7 = new javax.swing.JScrollPane();
        issuedBooksTable = new rojeru_san.complementos.RSTableMetro();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBookName = new app.bolivia.swing.JCTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        butIssueBook1 = new necesario.RSMaterialButtonCircle();
        txtStudentName = new app.bolivia.swing.JCTextField();
        jLabel16 = new javax.swing.JLabel();
        txtIssueDate = new app.bolivia.swing.JCTextField();
        jLabel18 = new javax.swing.JLabel();
        txtReturnDate = new app.bolivia.swing.JCTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtStatus = new app.bolivia.swing.JCTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(101, 0, 101));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/ReturnBook/icons8_important_book_100px.png"))); // NOI18N
        jLabel2.setText("Serlect A Book And student From The table");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 8, 0, new java.awt.Color(101, 0, 101)));

        booksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Book ID", "Book Name", "Author", "Quanitity"
            }
        ));
        booksTable.setColorBackgoundHead(new java.awt.Color(101, 0, 101));
        booksTable.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        booksTable.setFuenteFilas(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        booksTable.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        booksTable.setFuenteHead(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        booksTable.setRowHeight(40);
        booksTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booksTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(booksTable);

        studentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student ID", "Student Name", "Education Level", "Major"
            }
        ));
        studentsTable.setColorBackgoundHead(new java.awt.Color(101, 0, 101));
        studentsTable.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        studentsTable.setFuenteFilas(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        studentsTable.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        studentsTable.setFuenteHead(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        studentsTable.setRowHeight(40);
        studentsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentsTableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(studentsTable);

        issuedBooksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Book Name", "Student Name", "Issue Date", "Due Date", "Status"
            }
        ));
        issuedBooksTable.setColorBackgoundHead(new java.awt.Color(101, 0, 101));
        issuedBooksTable.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        issuedBooksTable.setFuenteFilas(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        issuedBooksTable.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        issuedBooksTable.setFuenteHead(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        issuedBooksTable.setRowHeight(40);
        issuedBooksTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                issuedBooksTableMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(issuedBooksTable);

        jPanel4.setBackground(new java.awt.Color(102, 153, 255));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/ManageBooks/icons8_back_to_48px.png"))); // NOI18N
        jLabel1.setText("Back");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        jLabel48.setBackground(new java.awt.Color(120, 120, 120));
        jLabel48.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("Students Info");

        jLabel49.setBackground(new java.awt.Color(120, 120, 120));
        jLabel49.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setText("Issued Books Info Select From here");

        jLabel50.setBackground(new java.awt.Color(120, 120, 120));
        jLabel50.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 0, 0));
        jLabel50.setText("Books Info");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel48)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1120, Short.MAX_VALUE)
                                .addComponent(jScrollPane5)
                                .addComponent(jScrollPane7))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel49))
                            .addComponent(jLabel50)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1150, 950));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(101, 0, 101));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/ReturnBook/icons8_book_100px_2.png"))); // NOI18N
        jLabel3.setText("Return Book");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 8, 0, new java.awt.Color(101, 0, 101)));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 50, -1, -1));

        txtBookName.setEditable(false);
        txtBookName.setBackground(new java.awt.Color(255, 255, 255));
        txtBookName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(101, 0, 101)));
        txtBookName.setForeground(new java.awt.Color(0, 0, 0));
        txtBookName.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        txtBookName.setPlaceholder("Book Name...");
        txtBookName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtBookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 340, 320, -1));

        jLabel15.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(101, 0, 101));
        jLabel15.setText("Book Name:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 350, 140, -1));

        jLabel17.setFont(new java.awt.Font("Malgun Gothic", 3, 25)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Signup/icons8_multiply_48px.png"))); // NOI18N
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1800, 0, -1, -1));

        butIssueBook1.setBackground(new java.awt.Color(101, 0, 101));
        butIssueBook1.setText("Return Book");
        butIssueBook1.setToolTipText("");
        butIssueBook1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butIssueBook1ActionPerformed(evt);
            }
        });
        jPanel1.add(butIssueBook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 740, 500, 90));

        txtStudentName.setEditable(false);
        txtStudentName.setBackground(new java.awt.Color(255, 255, 255));
        txtStudentName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(101, 0, 101)));
        txtStudentName.setForeground(new java.awt.Color(0, 0, 0));
        txtStudentName.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        txtStudentName.setPlaceholder("Student Name ...");
        txtStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtStudentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 420, 320, -1));

        jLabel16.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(101, 0, 101));
        jLabel16.setText("Student Name :");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 430, 180, -1));

        txtIssueDate.setEditable(false);
        txtIssueDate.setBackground(new java.awt.Color(255, 255, 255));
        txtIssueDate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(101, 0, 101)));
        txtIssueDate.setForeground(new java.awt.Color(0, 0, 0));
        txtIssueDate.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        txtIssueDate.setPlaceholder("Issue Date ...");
        jPanel1.add(txtIssueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 490, 320, -1));

        jLabel18.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(101, 0, 101));
        jLabel18.setText("Issue Date :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 500, 150, -1));

        txtReturnDate.setEditable(false);
        txtReturnDate.setBackground(new java.awt.Color(255, 255, 255));
        txtReturnDate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(101, 0, 101)));
        txtReturnDate.setForeground(new java.awt.Color(0, 0, 0));
        txtReturnDate.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        txtReturnDate.setPlaceholder("Retrun Date ...");
        txtReturnDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReturnDateActionPerformed(evt);
            }
        });
        jPanel1.add(txtReturnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 560, 320, -1));

        jLabel19.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(101, 0, 101));
        jLabel19.setText("Return Date :");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 570, 170, -1));

        jLabel20.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(101, 0, 101));
        jLabel20.setText("Status:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 630, 120, -1));

        txtStatus.setEditable(false);
        txtStatus.setBackground(new java.awt.Color(255, 255, 255));
        txtStatus.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(101, 0, 101)));
        txtStatus.setForeground(new java.awt.Color(0, 0, 0));
        txtStatus.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        txtStatus.setPlaceholder("Status ...");
        txtStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusActionPerformed(evt);
            }
        });
        jPanel1.add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 620, 320, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBookNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookNameActionPerformed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked

        HomePage homePage = new HomePage();
        homePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel4MouseClicked

    private void butIssueBook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butIssueBook1ActionPerformed
//       DefaultTableModel  defaultTableModel = (DefaultTableModel)booksTable.getModel();
//             String bookId1 =  defaultTableModel.getValueAt(booksTable.getSelectedRow(), 0).toString();
//             String bookName1 =  defaultTableModel.getValueAt(booksTable.getSelectedRow(), 1).toString();
//             String bookAuthor1 =  defaultTableModel.getValueAt(booksTable.getSelectedRow(), 2).toString();
//             String bookQuantity1 =  defaultTableModel.getValueAt(booksTable.getSelectedRow(), 3).toString();
//             int newQuantity = Integer.parseInt(bookQuantity1)-1;
//            fileAccess.editBooksQuantity(fileAccess.FILEBOOK, bookQuantity1 , 5, bookId1,bookName1, bookAuthor1,newQuantity);
        fileAccess.removeRecords("issuedBooks.txt", txtBookName.getText(), 1, "\t");
        controller.addReturndBook(txtBookName.getText(), txtStudentName.getText(), txtIssueDate.getText(), txtReturnDate.getText(), "Returned");
         String coltitle2[] = {"Book Name", "Student Name", "Issued Date", "Return Date","Status"};
        String data2[][] = controller.getIssuedBooksdata();
        DefaultTableModel model2 = new DefaultTableModel(data2, coltitle2);
        issuedBooksTable.setModel(model2);
    }//GEN-LAST:event_butIssueBook1ActionPerformed

    private void booksTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booksTableMouseClicked
        DefaultTableModel  defaultTableModel = (DefaultTableModel)booksTable.getModel();
        String bookID =  defaultTableModel.getValueAt(booksTable.getSelectedRow(), 0).toString();
        // set the data on the lables
        txtBookName.setText(bookID);
    }//GEN-LAST:event_booksTableMouseClicked

    private void studentsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentsTableMouseClicked
        DefaultTableModel  defaultTableModel = (DefaultTableModel)studentsTable.getModel();
        String studentID =  defaultTableModel.getValueAt(studentsTable.getSelectedRow(), 0).toString();

        // set the data on the lables
        txtStudentName.setText(studentID);
    }//GEN-LAST:event_studentsTableMouseClicked

    private void issuedBooksTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_issuedBooksTableMouseClicked
    DefaultTableModel  defaultTableModel = (DefaultTableModel)issuedBooksTable.getModel();
        String BookName =  defaultTableModel.getValueAt(issuedBooksTable.getSelectedRow(), 0).toString();
        String studentName =  defaultTableModel.getValueAt(issuedBooksTable.getSelectedRow(), 1).toString();
        String IssueDate =  defaultTableModel.getValueAt(issuedBooksTable.getSelectedRow(), 2).toString();
        String ReturnDate =  defaultTableModel.getValueAt(issuedBooksTable.getSelectedRow(), 3).toString();
        String stat =  defaultTableModel.getValueAt(issuedBooksTable.getSelectedRow(), 4).toString();

        // set the data on the lables
        txtBookName.setText(BookName);
        txtStudentName.setText(studentName);
        txtIssueDate.setText(IssueDate);
        txtReturnDate.setText(ReturnDate);
        txtStatus.setText(stat);
    }//GEN-LAST:event_issuedBooksTableMouseClicked

    private void txtStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentNameActionPerformed

    private void txtReturnDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReturnDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReturnDateActionPerformed

    private void txtStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.complementos.RSTableMetro booksTable;
    private necesario.RSMaterialButtonCircle butIssueBook1;
    private rojeru_san.complementos.RSTableMetro issuedBooksTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private rojeru_san.complementos.RSTableMetro studentsTable;
    private app.bolivia.swing.JCTextField txtBookName;
    private app.bolivia.swing.JCTextField txtIssueDate;
    private app.bolivia.swing.JCTextField txtReturnDate;
    private app.bolivia.swing.JCTextField txtStatus;
    private app.bolivia.swing.JCTextField txtStudentName;
    // End of variables declaration//GEN-END:variables
}
